name: install

on:
  push:
  pull_request:

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Run pre-commit on all files
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files --show-diff-on-failure

  cleanup-before:
    uses: ./.github/workflows/_cleanup.yml
    with:
      when: "before"

  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }} - ${{ matrix.env }}
    needs: [pre-commit, cleanup-before]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        py:
          - "3.11"
          - "3.10"
        env:
          - pip
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Conda
        if: matrix.env == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.py }}
          miniconda-version: "latest"
          activate-environment: test-env
          auto-update-conda: true

      - name: Setup Python for pip
        if: matrix.env == 'pip'
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.py }}

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install pufferlib
        run: pip install -e .

  cleanup-after:
    if: always()
    needs: test
    uses: ./.github/workflows/_cleanup.yml
    with:
      when: "after"
